- name: Ensure app dir exists
  file:
    path: /home/alumno/apps/myapp
    state: directory
    owner: alumno
    group: alumno
    mode: "0755"

- name: Checkout app code
  git:
    repo: "https://github.com/Felipelb47/test-ansible.git"
    dest: /home/alumno/apps/myapp
    version: "{{ git_ref | default('main') }}"
    force: yes
  become: no

- name: Install npm dependencies
  command: npm install
  args:
    chdir: /home/alumno/apps/myapp/app

- name: Copy systemd service file
  template:
    src: node-app.service.j2
    dest: /etc/systemd/system/myapp.service
  become: yes
  notify: Reload systemd

- name: Ensure service is started and enabled
  systemd:
    name: myapp
    state: started
    enabled: yes
  become: yes
